# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bunga.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bunga.proto',
  package='bunga',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x62unga.proto\x12\x05\x62unga\"U\n\x0e\x43lientToServer\x12\x37\n\x13\x65xecute_command_req\x18\x01 \x01(\x0b\x32\x18.bunga.ExecuteCommandReqH\x00\x42\n\n\x08messages\"U\n\x0eServerToClient\x12\x37\n\x13\x65xecute_command_rsp\x18\x01 \x01(\x0b\x32\x18.bunga.ExecuteCommandRspH\x00\x42\n\n\x08messages\"$\n\x11\x45xecuteCommandReq\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"\x86\x01\n\x11\x45xecuteCommandRsp\x12+\n\x04kind\x18\x01 \x01(\x0e\x32\x1d.bunga.ExecuteCommandRsp.Kind\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"%\n\x04Kind\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\n\n\x06OUTPUT\x10\x02\x62\x06proto3')
)



_EXECUTECOMMANDRSP_KIND = _descriptor.EnumDescriptor(
  name='Kind',
  full_name='bunga.ExecuteCommandRsp.Kind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUTPUT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=332,
  serialized_end=369,
)
_sym_db.RegisterEnumDescriptor(_EXECUTECOMMANDRSP_KIND)


_CLIENTTOSERVER = _descriptor.Descriptor(
  name='ClientToServer',
  full_name='bunga.ClientToServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='execute_command_req', full_name='bunga.ClientToServer.execute_command_req', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='messages', full_name='bunga.ClientToServer.messages',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=22,
  serialized_end=107,
)


_SERVERTOCLIENT = _descriptor.Descriptor(
  name='ServerToClient',
  full_name='bunga.ServerToClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='execute_command_rsp', full_name='bunga.ServerToClient.execute_command_rsp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='messages', full_name='bunga.ServerToClient.messages',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=109,
  serialized_end=194,
)


_EXECUTECOMMANDREQ = _descriptor.Descriptor(
  name='ExecuteCommandReq',
  full_name='bunga.ExecuteCommandReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='bunga.ExecuteCommandReq.command', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=232,
)


_EXECUTECOMMANDRSP = _descriptor.Descriptor(
  name='ExecuteCommandRsp',
  full_name='bunga.ExecuteCommandRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='bunga.ExecuteCommandRsp.kind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output', full_name='bunga.ExecuteCommandRsp.output', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='bunga.ExecuteCommandRsp.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXECUTECOMMANDRSP_KIND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=369,
)

_CLIENTTOSERVER.fields_by_name['execute_command_req'].message_type = _EXECUTECOMMANDREQ
_CLIENTTOSERVER.oneofs_by_name['messages'].fields.append(
  _CLIENTTOSERVER.fields_by_name['execute_command_req'])
_CLIENTTOSERVER.fields_by_name['execute_command_req'].containing_oneof = _CLIENTTOSERVER.oneofs_by_name['messages']
_SERVERTOCLIENT.fields_by_name['execute_command_rsp'].message_type = _EXECUTECOMMANDRSP
_SERVERTOCLIENT.oneofs_by_name['messages'].fields.append(
  _SERVERTOCLIENT.fields_by_name['execute_command_rsp'])
_SERVERTOCLIENT.fields_by_name['execute_command_rsp'].containing_oneof = _SERVERTOCLIENT.oneofs_by_name['messages']
_EXECUTECOMMANDRSP.fields_by_name['kind'].enum_type = _EXECUTECOMMANDRSP_KIND
_EXECUTECOMMANDRSP_KIND.containing_type = _EXECUTECOMMANDRSP
DESCRIPTOR.message_types_by_name['ClientToServer'] = _CLIENTTOSERVER
DESCRIPTOR.message_types_by_name['ServerToClient'] = _SERVERTOCLIENT
DESCRIPTOR.message_types_by_name['ExecuteCommandReq'] = _EXECUTECOMMANDREQ
DESCRIPTOR.message_types_by_name['ExecuteCommandRsp'] = _EXECUTECOMMANDRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientToServer = _reflection.GeneratedProtocolMessageType('ClientToServer', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTTOSERVER,
  __module__ = 'bunga_pb2'
  # @@protoc_insertion_point(class_scope:bunga.ClientToServer)
  ))
_sym_db.RegisterMessage(ClientToServer)

ServerToClient = _reflection.GeneratedProtocolMessageType('ServerToClient', (_message.Message,), dict(
  DESCRIPTOR = _SERVERTOCLIENT,
  __module__ = 'bunga_pb2'
  # @@protoc_insertion_point(class_scope:bunga.ServerToClient)
  ))
_sym_db.RegisterMessage(ServerToClient)

ExecuteCommandReq = _reflection.GeneratedProtocolMessageType('ExecuteCommandReq', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTECOMMANDREQ,
  __module__ = 'bunga_pb2'
  # @@protoc_insertion_point(class_scope:bunga.ExecuteCommandReq)
  ))
_sym_db.RegisterMessage(ExecuteCommandReq)

ExecuteCommandRsp = _reflection.GeneratedProtocolMessageType('ExecuteCommandRsp', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTECOMMANDRSP,
  __module__ = 'bunga_pb2'
  # @@protoc_insertion_point(class_scope:bunga.ExecuteCommandRsp)
  ))
_sym_db.RegisterMessage(ExecuteCommandRsp)


# @@protoc_insertion_point(module_scope)
