TESTS += test_server.c
INC += ../include
INC += ../../3pp/include
SRC += ../src/bunga_server_linux.c
LIBS += pthread
NO_IMPLEMENTATION += ml_*
NO_IMPLEMENTATION += bunga_server_*
NO_IMPLEMENTATION += bunga_log_entry_ind_text_alloc

include test.mk
